### ISSUE TITLE
Release 0.1.0-beta of Swift 

### ISSUE THREAD

**Issue by PierreBrisorgueil** [weareopensource/weareopensource.github.io#5]
- [x] docs review https://github.com/weareopensource/Swift/issues/50 https://github.com/weareopensource/Swift/issues/49 https://github.com/weareopensource/Swift/issues/48
- [x] init git https://github.com/weareopensource/Swift/issues/1
- [x] init IOS project https://github.com/weareopensource/Swift/issues/2 
- [x] logo & load screen https://github.com/weareopensource/Swift/issues/4  
- [x] README https://github.com/weareopensource/Swift/issues/6
- [x] Add Badges https://github.com/weareopensource/Swift/issues/7 
- [x] Travis https://github.com/weareopensource/Swift/issues/8
- [x] init knowledges https://github.com/weareopensource/Swift/issues/27
- [x] eat(architecture): init v0  https://github.com/weareopensource/Swift/issues/3
- [x] feat(auth): init https://github.com/weareopensource/Swift/issues/9
- [x] feat(tasks): List https://github.com/weareopensource/Swift/issues/11
- [x] feat(tasks): Add https://github.com/weareopensource/Swift/issues/12
- [x] feat(tasks): Delete https://github.com/weareopensource/Swift/issues/13
- [x] feat(tasks): Edit https://github.com/weareopensource/Swift/issues/14
- [x] feat(localizations): initialisation https://github.com/weareopensource/Swift/issues/32
- [x] feat(flow): init flow and rooting system https://github.com/weareopensource/Swift/issues/26
- [x] feat(global): init logger service https://github.com/weareopensource/Swift/issues/38
- [x] feat(global): init config files https://github.com/weareopensource/Swift/issues/37
