### ISSUE TITLE
Release 0.1.0-beta of Angular

### ISSUE THREAD

**Issue by PierreBrisorgueil** [weareopensource/weareopensource.github.io#6]
https://github.com/weareopensource/Angular/milestone/1

- [ ] feat(global): upgrade all dependencies https://github.com/weareopensource/Angular/issues/134
- [ ] fix(auth): Refresh broke application https://github.com/weareopensource/Angular/issues/135
- [ ] fix(tasks): delete don't refresh list  https://github.com/weareopensource/Angular/issues/136
- [x] feat(global): add snyk  https://github.com/weareopensource/Angular/issues/137
- [ ] feat(global): add coverage https://github.com/weareopensource/Angular/issues/139
- [ ] feat(global): add greenkeeper https://github.com/weareopensource/Angular/issues/140
- [x] feat(global): add codeClimate #141 https://github.com/weareopensource/Angular/issues/141
- [x] feat(global): review readme like node example https://github.com/weareopensource/Angular/issues/143
- [x] refactor(global): check travis https://github.com/weareopensource/Angular/issues/138
- [x] feat(global): add dependencies check : https://github.com/weareopensource/Angular/issues/142
